POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento 3",
  "details": null,
  "maximumAttendees": 1
}

###
POST http://localhost:3333/events/4d622616-8ee8-4e06-9a05-fe7f1a5c8763/attendees
Content-Type: application/json

{
  "name": "Joao",
  "email": "joaojpmoreira25@gmail.com"
}

###
GET  http://localhost:3333/events/4d622616-8ee8-4e06-9a05-fe7f1a5c8763

###
GET http://localhost:3333/attendees/3/badge