POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Helmet Royale",
  "details": "Torneio BattleRock",
  "maximumAttendees": 4
}

###
POST http://localhost:3333/events/233bed64-8793-48b4-83d6-19fb124b8216/attendees
Content-Type: application/json

{
  "name": "Ulisses",
  "email": "ulisses@gmail.com"
}

###
GET  http://localhost:3333/events/233bed64-8793-48b4-83d6-19fb124b8216

###
GET http://localhost:3333/attendees/6/badge

###
GET http://localhost:3333/attendees/7/check-in

###
GET http://localhost:3333/events/233bed64-8793-48b4-83d6-19fb124b8216/attendees